# Cálculo matricial con Numpy
> Vista de la librería para cálculo matricial

- toc: true 
- badges: true
- comments: true
- categories: [deepmaxfn, python, numpy]
- image: images/numpy-icon.png

## 1. Resumen

`Vamos a ver la librería de calculo matricial Numpy.`

![numpy](https://techscript24.com/wp-content/uploads/2020/10/86498201-a8bd8680-bd39-11ea-9d08-66b610a8dc01.png)

## 2. ¿Qué es Numpy?

Numpy es una librería de Python diseñada para realizar cálculo matricial. EL cálculo matricial es algo que se utiliza mucho en ciencia en general y en data science en particular, por lo que es necesario tener una librería que haga esto muy bien.

Su nombre quiere decir numerical python

Numpy tiene el objetivo de realizar el cálculo matricial mucho más rápido que con las listas de Python, pero ¿cómo es esto posible? Por dos razones, una es que la parte de su código que realiza este cálculo está escrito en C/C++ (mucho más rápido que Python) y además los datos de las matrices se almacenan en memoria de manera continua, al contrario que las listas de Python, lo que hace que sea mucho más rápido manipularlos

### 2.1. Numpy como `np`

Generalmente a la hora de importar Numpy se suele importar con el alias de `np`

In [1]:
import numpy as np

print(np.__version__)

1.19.5


## 3. Matrices en Numpy

En Numpy una matriz es un objeto `ndarray`

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Con el método `array()` se pueden crear `ndarray`s introduciendo listas de Python (como el ejemplo anterior), o tuplas

In [3]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### 3.1. Dimensiones de las matrices

En Numpy podemos crear matrices de cualquier dimensión. Para obtener la dimensión de un array utilizamos el método `ndim`

Matriz de dimensión 0, lo que equivaldría a un número

In [9]:
arr = np.array(42)

print(arr)
print(arr.ndim)

42
0


Matriz de dimensión 1, lo que equivaldría a un vector

In [10]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


Matriz de dimensión 2, lo que equivaldría a una matriz

In [12]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr)
print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


Matriz de dimensión 3

In [14]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

print(arr)
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
3


Matriz de dimensión N. A la hora de crear `ndarray`s se puede establecer el número de dimensiones mediante el parámetro `ndim`

In [15]:
arr = np.array([1, 2, 3, 4, 5], ndmin=6)

print(arr)
print(arr.ndim)

[[[[[[1 2 3 4 5]]]]]]
6
